### ISSUE TITLE
couldn't find "added upsampling nonlinearities", and patch size vs batch size

### ISSUE THREAD

**Issue by oldie77** [nmhkahn/PCARN-pytorch#2]
First of all big thanks for your work and for sharing it so openly!

Two questions, if you don't mind.

1) In your paper you're writing:

> Addionally, we attach additional nonlinearities
> in the upsampling unit in order to increase the
> expressive power of the network.

But when comparing the PCARN to the CARN network structure, I can't actually see any difference in the upsampling unit at all. They seem identical to me. Have I missed something?

2) I noticed that you're using a patch and batch size of 64 for CARN, but you're using a patch size of 48 for PCARN, while still using a batch size of 64. I'm wondering: Did you drop down to a patch size of 48 due to VRAM limitations? Or did you get better results that way?

Generally, can you advise if it's better to drop batch size or patch size, if VRAM runs short? I guess dropping batch size mainly reduces training efficiency (more iterations necessary to achieve the same result), while dropping patch size might reduce quality a bit? This is just a guess on my part, though. Just wondering what your experience is with different batch and patch sizes?

**Comment by nmhkahn** [comment]
Hi.
1. The first announced version of CARN didn't use ReLU in the upsample block. But while we doing this work, found that it's better to add ReLU in the upsample block and update CARN as well.
That's why CARN and PCARN have identical code. I think that it makes confusing to readers; anyway.

2. The main reason is that using a large patch size requires long long training time, and it is more critical to this project since both generator and discriminator have to be calculated.

We didn't put it the experimental result but found that patch size larger than 48 doesn't improve the performance while smaller patch size (>48) harms the quality.
It because our network has only 19 layers before the upsample block, which makes the receptive field as 39, so that larger patch size is meaningless.

So, if when you are short of VRAM, your choice depends on the network depth; if you have more depth like recent SOTA methods like EDSR, larger patch size is meaningful. But since training time is very very slow, I recommend to set the size up to 48.

**Comment by oldie77** [comment]
Thank you very much!!
